#1)
print (True or False)
print (False or True)
print (True or True)

#2) 
print (True or True)
print (False or False)
print (True or False)
print (False or True)
print (True and True)
print (False and False)
print (True and False)
print (False and True)

#3)
age =int(input("please enter your age: "))
name = (input("please enter your name: "))
print (name = "giorgi")
print (age = 18)